# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ADC_DATA_CAPTURE_CONSTAIN.xdc

# Block Designs: bd/ILA/ILA.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ILA || ORIG_REF_NAME==ILA} -quiet] -quiet

# IP: bd/ILA/ip/ILA_ila_0_0/ILA_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ILA_ila_0_0 || ORIG_REF_NAME==ILA_ila_0_0} -quiet] -quiet

# XDC: c:/My Xillinx/Vivado/afe7225/project_adc_capture/project_adc_capture.gen/sources_1/bd/ILA/ILA_ooc.xdc
