# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/My Xillinx/Vivado/afe7225/project_adc_capture/project_adc_capture.srcs/sources_1/bd/ILA/ip/ILA_ila_0_0/ILA_ila_0_0.xci
# IP: The module: 'ILA_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/My Xillinx/Vivado/afe7225/project_adc_capture/project_adc_capture.gen/sources_1/bd/ILA/ip/ILA_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ILA_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/My Xillinx/Vivado/afe7225/project_adc_capture/project_adc_capture.gen/sources_1/bd/ILA/ip/ILA_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ILA_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/My Xillinx/Vivado/afe7225/project_adc_capture/project_adc_capture.gen/sources_1/bd/ILA/ip/ILA_ila_0_0/ILA_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ILA_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/My Xillinx/Vivado/afe7225/project_adc_capture/project_adc_capture.srcs/sources_1/bd/ILA/ip/ILA_ila_0_0/ILA_ila_0_0.xci
# IP: The module: 'ILA_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/My Xillinx/Vivado/afe7225/project_adc_capture/project_adc_capture.gen/sources_1/bd/ILA/ip/ILA_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ILA_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/My Xillinx/Vivado/afe7225/project_adc_capture/project_adc_capture.gen/sources_1/bd/ILA/ip/ILA_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ILA_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/My Xillinx/Vivado/afe7225/project_adc_capture/project_adc_capture.gen/sources_1/bd/ILA/ip/ILA_ila_0_0/ILA_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ILA_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
