create_clock -period 10.000 -name CLK_IN -waveform {0.000 5.000} -add [get_ports CLK_IN]
set_property CLOCK_DEDICATED_ROUTE ANY_CMT_COLUMN [get_nets -of [get_pins ADC_DATA_CAPTURING/BUFG_SYNC/O]]

set_property -dict {PACKAGE_PIN F17 IOSTANDARD LVCMOS33} [get_ports CLK_IN]
set_property -dict {PACKAGE_PIN C24 IOSTANDARD LVCMOS33} [get_ports RST]

set_property -dict {PACKAGE_PIN W25 IOSTANDARD LVDS_25} [get_ports DCLK_p]
set_property -dict {PACKAGE_PIN W26 IOSTANDARD LVDS_25} [get_ports DCLK_n]

set_property -dict {PACKAGE_PIN AA25 IOSTANDARD LVDS_25} [get_ports FCLK_p]
set_property -dict {PACKAGE_PIN AB25 IOSTANDARD LVDS_25} [get_ports FCLK_n]

set_property -dict {PACKAGE_PIN P24 IOSTANDARD LVDS_25} [get_ports {DB_p[0]}]
set_property -dict {PACKAGE_PIN P23 IOSTANDARD LVDS_25} [get_ports {DB_p[1]}]

set_property -dict {PACKAGE_PIN AD25 IOSTANDARD LVDS_25} [get_ports {DA_p[0]}]
set_property -dict {PACKAGE_PIN AC23 IOSTANDARD LVDS_25} [get_ports {DA_p[1]}]

#set_property -dict {PACKAGE_PIN  V13 IOSTANDARD LVCMOS15} [get_ports {DA[0]}]
#set_property -dict {PACKAGE_PIN AE17 IOSTANDARD LVCMOS15} [get_ports {DA[1]}]
#set_property -dict {PACKAGE_PIN AF17 IOSTANDARD LVCMOS15} [get_ports {DA[2]}]
#set_property -dict {PACKAGE_PIN AF14 IOSTANDARD LVCMOS15} [get_ports {DA[3]}]
#set_property -dict {PACKAGE_PIN AF15 IOSTANDARD LVCMOS15} [get_ports {DA[4]}]
#set_property -dict {PACKAGE_PIN AE18 IOSTANDARD LVCMOS15} [get_ports {DA[5]}]
#set_property -dict {PACKAGE_PIN AF18 IOSTANDARD LVCMOS15} [get_ports {DA[6]}]
#set_property -dict {PACKAGE_PIN AD15 IOSTANDARD LVCMOS15} [get_ports {DA[7]}]
#set_property -dict {PACKAGE_PIN AE15 IOSTANDARD LVCMOS15} [get_ports {DA[8]}]
#set_property -dict {PACKAGE_PIN AF19 IOSTANDARD LVCMOS15} [get_ports {DA[9]}]
#set_property -dict {PACKAGE_PIN AF20 IOSTANDARD LVCMOS15} [get_ports {DA[10]}]
#set_property -dict {PACKAGE_PIN AD16 IOSTANDARD LVCMOS15} [get_ports {DA[11]}]

#set_property -dict {PACKAGE_PIN AD14 IOSTANDARD LVCMOS15} [get_ports {DB[0]}]
#set_property -dict {PACKAGE_PIN Y15 IOSTANDARD  LVCMOS15} [get_ports {DB[1]}]
#set_property -dict {PACKAGE_PIN Y16 IOSTANDARD  LVCMOS15} [get_ports {DB[2]}]
#set_property -dict {PACKAGE_PIN AB14 IOSTANDARD LVCMOS15} [get_ports {DB[3]}]
#set_property -dict {PACKAGE_PIN AB15 IOSTANDARD LVCMOS15} [get_ports {DB[4]}]
#set_property -dict {PACKAGE_PIN AA17 IOSTANDARD LVCMOS15} [get_ports {DB[5]}]
#set_property -dict {PACKAGE_PIN AA18 IOSTANDARD LVCMOS15} [get_ports {DB[6]}]
#set_property -dict {PACKAGE_PIN AB16 IOSTANDARD LVCMOS15} [get_ports {DB[7]}]
#set_property -dict {PACKAGE_PIN AC16 IOSTANDARD LVCMOS15} [get_ports {DB[8]}]
#set_property -dict {PACKAGE_PIN AC18 IOSTANDARD LVCMOS15} [get_ports {DB[9]}]
#set_property -dict {PACKAGE_PIN AD18 IOSTANDARD LVCMOS15} [get_ports {DB[10]}]
#set_property -dict {PACKAGE_PIN AB17 IOSTANDARD LVCMOS15} [get_ports {DB[11]}]

set_property -dict {PACKAGE_PIN AA2 IOSTANDARD LVCMOS15} [get_ports DCLK_DONE]
set_property -dict {PACKAGE_PIN AD5 IOSTANDARD LVCMOS15} [get_ports FCLK_DONE]

#set_property MARK_DEBUG true [get_nets {ADC_DATA_CAPTURING/BIT_CLOCK_SYNC/DCLK_reg[0]}]
#set_property MARK_DEBUG true [get_nets {ADC_DATA_CAPTURING/BIT_CLOCK_SYNC/DCLK_reg[1]}]
#set_property MARK_DEBUG true [get_nets {ADC_DATA_CAPTURING/BIT_CLOCK_SYNC/DCLK_reg[2]}]
#set_property MARK_DEBUG true [get_nets {ADC_DATA_CAPTURING/BIT_CLOCK_SYNC/DCLK_reg[3]}]
#set_property MARK_DEBUG true [get_nets {ADC_DATA_CAPTURING/BIT_CLOCK_SYNC/DCLK_reg[4]}]
#set_property MARK_DEBUG true [get_nets {ADC_DATA_CAPTURING/BIT_CLOCK_SYNC/DCLK_reg[5]}]
#set_property MARK_DEBUG true [get_nets {ADC_DATA_CAPTURING/FRAME_ALIGN/FCLK_reg[0]}]
#set_property MARK_DEBUG true [get_nets {ADC_DATA_CAPTURING/FRAME_ALIGN/FCLK_reg[1]}]
#set_property MARK_DEBUG true [get_nets {ADC_DATA_CAPTURING/FRAME_ALIGN/FCLK_reg[2]}]
#set_property MARK_DEBUG true [get_nets {ADC_DATA_CAPTURING/FRAME_ALIGN/FCLK_reg[3]}]
#set_property MARK_DEBUG true [get_nets {ADC_DATA_CAPTURING/FRAME_ALIGN/FCLK_reg[4]}]
#set_property MARK_DEBUG true [get_nets {ADC_DATA_CAPTURING/FRAME_ALIGN/FCLK_reg[5]}]
#set_property MARK_DEBUG true [get_nets {ADC_DATA_CAPTURING/DATA_RECEIVE/B_reg_reg[11]_0[0]}]
#set_property MARK_DEBUG true [get_nets {ADC_DATA_CAPTURING/DATA_RECEIVE/B_reg_reg[11]_0[2]}]
#set_property MARK_DEBUG true [get_nets {ADC_DATA_CAPTURING/DATA_RECEIVE/B_reg_reg[11]_0[3]}]
#set_property MARK_DEBUG true [get_nets {ADC_DATA_CAPTURING/DATA_RECEIVE/B_reg_reg[11]_0[4]}]
#set_property MARK_DEBUG true [get_nets {ADC_DATA_CAPTURING/DATA_RECEIVE/B_reg_reg[11]_0[8]}]
#set_property MARK_DEBUG true [get_nets {ADC_DATA_CAPTURING/DATA_RECEIVE/B_reg_reg[11]_0[9]}]
#set_property MARK_DEBUG true [get_nets {ADC_DATA_CAPTURING/DATA_RECEIVE/B_reg_reg[11]_0[10]}]
#set_property MARK_DEBUG true [get_nets {ADC_DATA_CAPTURING/DATA_RECEIVE/B_reg_reg[11]_0[1]}]
#set_property MARK_DEBUG true [get_nets {ADC_DATA_CAPTURING/DATA_RECEIVE/B_reg_reg[11]_0[5]}]
#set_property MARK_DEBUG true [get_nets {ADC_DATA_CAPTURING/DATA_RECEIVE/B_reg_reg[11]_0[6]}]
#set_property MARK_DEBUG true [get_nets {ADC_DATA_CAPTURING/DATA_RECEIVE/B_reg_reg[11]_0[7]}]
#set_property MARK_DEBUG true [get_nets {ADC_DATA_CAPTURING/DATA_RECEIVE/B_reg_reg[11]_0[11]}]
#set_property MARK_DEBUG true [get_nets {ADC_DATA_CAPTURING/DATA_RECEIVE/Q[1]}]
#set_property MARK_DEBUG true [get_nets {ADC_DATA_CAPTURING/DATA_RECEIVE/Q[3]}]
#set_property MARK_DEBUG true [get_nets {ADC_DATA_CAPTURING/DATA_RECEIVE/Q[5]}]
#set_property MARK_DEBUG true [get_nets {ADC_DATA_CAPTURING/DATA_RECEIVE/Q[6]}]
#set_property MARK_DEBUG true [get_nets {ADC_DATA_CAPTURING/DATA_RECEIVE/Q[7]}]
#set_property MARK_DEBUG true [get_nets {ADC_DATA_CAPTURING/DATA_RECEIVE/Q[0]}]
#set_property MARK_DEBUG true [get_nets {ADC_DATA_CAPTURING/DATA_RECEIVE/Q[2]}]
#set_property MARK_DEBUG true [get_nets {ADC_DATA_CAPTURING/DATA_RECEIVE/Q[4]}]
#set_property MARK_DEBUG true [get_nets {ADC_DATA_CAPTURING/DATA_RECEIVE/Q[8]}]
#set_property MARK_DEBUG true [get_nets {ADC_DATA_CAPTURING/DATA_RECEIVE/Q[9]}]
#set_property MARK_DEBUG true [get_nets {ADC_DATA_CAPTURING/DATA_RECEIVE/Q[10]}]
#set_property MARK_DEBUG true [get_nets {ADC_DATA_CAPTURING/DATA_RECEIVE/Q[11]}]
#create_debug_core u_ila_0 ila
#set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
#set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
#set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
#set_property C_DATA_DEPTH 131072 [get_debug_cores u_ila_0]
#set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
#set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
#set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
#set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
#set_property port_width 1 [get_debug_ports u_ila_0/clk]
#connect_debug_port u_ila_0/clk [get_nets [list ADC_DATA_CAPTURING/CLK_DIV]]
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
#set_property port_width 6 [get_debug_ports u_ila_0/probe0]
#connect_debug_port u_ila_0/probe0 [get_nets [list {ADC_DATA_CAPTURING/BIT_CLOCK_SYNC/DCLK_reg[0]} {ADC_DATA_CAPTURING/BIT_CLOCK_SYNC/DCLK_reg[1]} {ADC_DATA_CAPTURING/BIT_CLOCK_SYNC/DCLK_reg[2]} {ADC_DATA_CAPTURING/BIT_CLOCK_SYNC/DCLK_reg[3]} {ADC_DATA_CAPTURING/BIT_CLOCK_SYNC/DCLK_reg[4]} {ADC_DATA_CAPTURING/BIT_CLOCK_SYNC/DCLK_reg[5]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
#set_property port_width 12 [get_debug_ports u_ila_0/probe1]
#connect_debug_port u_ila_0/probe1 [get_nets [list {ADC_DATA_CAPTURING/DATA_RECEIVE/Q[0]} {ADC_DATA_CAPTURING/DATA_RECEIVE/Q[1]} {ADC_DATA_CAPTURING/DATA_RECEIVE/Q[2]} {ADC_DATA_CAPTURING/DATA_RECEIVE/Q[3]} {ADC_DATA_CAPTURING/DATA_RECEIVE/Q[4]} {ADC_DATA_CAPTURING/DATA_RECEIVE/Q[5]} {ADC_DATA_CAPTURING/DATA_RECEIVE/Q[6]} {ADC_DATA_CAPTURING/DATA_RECEIVE/Q[7]} {ADC_DATA_CAPTURING/DATA_RECEIVE/Q[8]} {ADC_DATA_CAPTURING/DATA_RECEIVE/Q[9]} {ADC_DATA_CAPTURING/DATA_RECEIVE/Q[10]} {ADC_DATA_CAPTURING/DATA_RECEIVE/Q[11]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
#set_property port_width 12 [get_debug_ports u_ila_0/probe2]
#connect_debug_port u_ila_0/probe2 [get_nets [list {ADC_DATA_CAPTURING/DATA_RECEIVE/B_reg_reg[11]_0[0]} {ADC_DATA_CAPTURING/DATA_RECEIVE/B_reg_reg[11]_0[1]} {ADC_DATA_CAPTURING/DATA_RECEIVE/B_reg_reg[11]_0[2]} {ADC_DATA_CAPTURING/DATA_RECEIVE/B_reg_reg[11]_0[3]} {ADC_DATA_CAPTURING/DATA_RECEIVE/B_reg_reg[11]_0[4]} {ADC_DATA_CAPTURING/DATA_RECEIVE/B_reg_reg[11]_0[5]} {ADC_DATA_CAPTURING/DATA_RECEIVE/B_reg_reg[11]_0[6]} {ADC_DATA_CAPTURING/DATA_RECEIVE/B_reg_reg[11]_0[7]} {ADC_DATA_CAPTURING/DATA_RECEIVE/B_reg_reg[11]_0[8]} {ADC_DATA_CAPTURING/DATA_RECEIVE/B_reg_reg[11]_0[9]} {ADC_DATA_CAPTURING/DATA_RECEIVE/B_reg_reg[11]_0[10]} {ADC_DATA_CAPTURING/DATA_RECEIVE/B_reg_reg[11]_0[11]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
#set_property port_width 6 [get_debug_ports u_ila_0/probe3]
#connect_debug_port u_ila_0/probe3 [get_nets [list {ADC_DATA_CAPTURING/FRAME_ALIGN/FCLK_reg[0]} {ADC_DATA_CAPTURING/FRAME_ALIGN/FCLK_reg[1]} {ADC_DATA_CAPTURING/FRAME_ALIGN/FCLK_reg[2]} {ADC_DATA_CAPTURING/FRAME_ALIGN/FCLK_reg[3]} {ADC_DATA_CAPTURING/FRAME_ALIGN/FCLK_reg[4]} {ADC_DATA_CAPTURING/FRAME_ALIGN/FCLK_reg[5]}]]
#set_property C_CLK_INPUT_FREQ_HZ 100000000 [get_debug_cores dbg_hub]
#set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
#set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
#connect_debug_port dbg_hub/clk [get_nets u_ila_0_CLK_DIV]
